SPRITE_SCALING = .5
AMMO_SCALE = 0.07
TILE_SCALING = .5
SPRITE_NATIVE_SIZE = 128
SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * SPRITE_SCALING)

DEFAULT_SCREEN_WIDTH = 800
DEFAULT_SCREEN_HEIGHT = 800
BORDER_WIDTH = 2048
BORDER_HEIGHT = 1536
MAP_WIDTH = 2016
MAP_HEIGHT = 1568
SCREEN_TITLE = "Final game"
VIEWPOINT_MARGIN = 20
CAMERA_SPEED = 0.3
GRID_PIXEL_SIZE = SPRITE_NATIVE_SIZE * TILE_SCALING

PLAYER_SPEED = 2.2
CLIMB_SPEED = 7.5
FALL_SPeED = 10.5
JUMP_SPEED = 8
PLAYER_SCALE = 0.405

UPDATES_PER_FRAME = 4
RIGHT_FACING = 0
LEFT_FACING = 1
UP_FACING = 2
DOWN_FACING = 3

ZOMBIE_COUNT = 5
AMMO_COUNT = 50
BULLET_SPEED = 10
GRAVITY = 1

ZOMBIE_SPEED = 3.0
