SPRITE_SCALING = .5
AMMO_SCALE = 0.07
TILE_SCALING = .5
SPRITE_NATIVE_SIZE = 128
SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * SPRITE_SCALING)

DEFAULT_SCREEN_WIDTH = 800
DEFAULT_SCREEN_HEIGHT = 800

SCREEN_TITLE = "Final game"
VIEWPOINT_MARGIN = 20
CAMERA_SPEED = 0.3
GRID_PIXEL_SIZE = SPRITE_NATIVE_SIZE * TILE_SCALING

PLAYER_SPEED = 2.2
CLIMB_SPEED = 7.5
FALL_SPeED = 10.5
JUMP_SPEED = 8
PLAYER_SCALE = 0.405
AMMO_COUNT_COLOR = (164, 0, 0)
RELOAD_COLOR = (194, 39, 0)

UPDATES_PER_FRAME = 4
RIGHT_FACING = 0
LEFT_FACING = 1
UP_FACING = 2
DOWN_FACING = 3

ZOMBIE_COUNT = 5
AMMO_COUNT = 25
BULLET_SPEED = 10
MAG_AMOUNT = 15
GRAVITY = 1

ZOMBIE_SPEED = 30.0
START_X = -855
END_X = 26495
